// Structured data and social-card data for a blog post, built as plain objects
// so they can be tested without rendering. PostArticle passes the result to
// <Seo>, and the prerender snapshot ships it in each post's static HTML, which
// is what non-JS readers (LinkedIn's unfurler, Bing, AI crawlers) see.
import { SITE_URL as SITE } from '../components/Seo';
import type { BlogPost } from './postContent';

const PERSON_ID = `${SITE}/#person`;
const WEBSITE_ID = `${SITE}/#website`;
const FAQ_HEADING = /^##\s+Frequently asked questions\s*$/im;

/** One PNG per post, generated by `npm run og` from the post title. */
export const postOgImagePath = (slug: string) => `/og/${slug}.png`;

export interface FaqEntry {
  question: string;
  answer: string;
}

// Plain text for JSON-LD: the answer shows up in search and AI results, where
// Markdown syntax would be noise.
const stripInlineMarkdown = (text: string) =>
  text
    .replace(/\[([^\]]+)\]\([^)\s]+\)/g, '$1')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/(?<![\w*])\*([^*\s][^*]*?)\*(?![\w*])/g, '$1')
    .replace(/\s+/g, ' ')
    .trim();

/**
 * The "## Frequently asked questions" section as question/answer pairs: each
 * "### " heading is a question, the text under it (until the next heading) its
 * answer. Returns [] when the post has no such section.
 */
export const extractFaq = (content: string): FaqEntry[] => {
  const start = content.search(FAQ_HEADING);
  if (start === -1) return [];
  const afterHeading = content.slice(start).split('\n').slice(1).join('\n');
  const nextSection = afterHeading.search(/^##\s/m);
  const section = nextSection === -1 ? afterHeading : afterHeading.slice(0, nextSection);

  return section
    .split(/^###\s+/m)
    .slice(1)
    .map((chunk) => {
      const [question, ...rest] = chunk.split('\n');
      return { question: stripInlineMarkdown(question), answer: stripInlineMarkdown(rest.join(' ')) };
    })
    .filter((entry) => entry.question && entry.answer);
};

export const buildPostJsonLd = (post: BlogPost) => {
  const url = `${SITE}/blog/${post.slug}`;
  const faq = extractFaq(post.content);

  const graph: Record<string, unknown>[] = [
    {
      '@type': 'BlogPosting',
      '@id': `${url}#article`,
      headline: post.title,
      description: post.description,
      abstract: post.excerpt,
      image: [`${SITE}${postOgImagePath(post.slug)}`],
      datePublished: post.publishedAt,
      dateModified: post.updatedAt ?? post.publishedAt,
      inLanguage: 'en',
      keywords: post.tags.join(', '),
      // The same Person entity index.html declares, so search engines and AI
      // systems tie every post to one author rather than to a bare name.
      author: { '@type': 'Person', '@id': PERSON_ID, name: 'Maksym Shykov', url: `${SITE}/` },
      publisher: { '@id': PERSON_ID },
      isPartOf: { '@id': WEBSITE_ID },
      mainEntityOfPage: url,
      url,
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE}/` },
        { '@type': 'ListItem', position: 2, name: 'Writing', item: `${SITE}/blog` },
        { '@type': 'ListItem', position: 3, name: post.title, item: url },
      ],
    },
  ];

  if (faq.length > 0) {
    graph.push({
      '@type': 'FAQPage',
      mainEntity: faq.map(({ question, answer }) => ({
        '@type': 'Question',
        name: question,
        acceptedAnswer: { '@type': 'Answer', text: answer },
      })),
    });
  }

  return { '@context': 'https://schema.org', '@graph': graph };
};
