sonar.organization=mshykov
sonar.projectKey=mshykov_shykov.dev
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=dist/**,node_modules/**
